name: Azure Pipelines
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Hosted Ubuntu 22
    steps:
    - task: CmdLine@2
      displayName: Install newman
      inputs:
        script: 'sudo npm install -g newman'
        workingDirectory: 'starter-code/automatedtesting/postman'
    - task: CmdLine@2
      displayName: Reun newman test
      continueOnError: true
      inputs:
        script: 'newman run json StarterAPIs.json'
        workingDirectory: 'starter-code/automatedtesting/postman'
    
    