name: Azure Pipelines
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: 'Hosted Ubuntu 1604'  # Corrected agent pool name
    steps:
    - task: CmdLine@2
      displayName: Install newman
      inputs:
        script: 'sudo npm install -g newman'
        workingDirectory: 'starter-code/automatedtesting/postman'
    - task: CmdLine@2
      displayName: Run newman test
      continueOnError: true
      inputs:
        script: 'newman run StarterAPIs.json'
        workingDirectory: 'starter-code/automatedtesting/postman'
